function daily(){
     document.getElementById("work").innerHTML = "5hrs"
     document.getElementById("work-sub").innerHTML = "Last Week - 7 horas"
     document.getElementById("play").innerHTML = "1hrs"
     document.getElementById("play-sub").innerHTML = "Last Week - 2 horas"
     document.getElementById("study").innerHTML = "0hrs"
     document.getElementById("study-sub").innerHTML = "Last Week - 1 horas"
     document.getElementById("exercise").innerHTML = "1hrs"
     document.getElementById("exercise-sub").innerHTML = "Last Week - 1 horas"
     document.getElementById("social").innerHTML = "1hrs"
     document.getElementById("social-sub").innerHTML = "Last Week - 3 horas"
     document.getElementById("self").innerHTML = "0hrs"
     document.getElementById("self-sub").innerHTML = "Last Week - 1 horas"
     document.getElementById("dia").style.color ="white"
     document.getElementById("semana").style.color ="rgba(255, 255, 255, 0.4)"
     document.getElementById("mes").style.color ="rgba(255, 255, 255, 0.4)"
}
function weekly(){
    document.getElementById("work").innerHTML = "32hrs"
    document.getElementById("work-sub").innerHTML = "Last Week - 36 horas"
    document.getElementById("play").innerHTML = "10hrs"
    document.getElementById("play-sub").innerHTML = "Last Week - 8 horas"
    document.getElementById("study").innerHTML = "4hrs"
    document.getElementById("study-sub").innerHTML = "Last Week - 7 horas"
    document.getElementById("exercise").innerHTML = "4hrs"
    document.getElementById("exercise-sub").innerHTML = "Last Week - 5 horas"
    document.getElementById("social").innerHTML = "5hrs"
    document.getElementById("social-sub").innerHTML = "Last Week - 10 horas"
    document.getElementById("self").innerHTML = "2hrs"
    document.getElementById("self-sub").innerHTML = "Last Week - 2 horas"
    document.getElementById("dia").style.color ="rgba(255, 255, 255, 0.4)"
    document.getElementById("semana").style.color ="white"
    document.getElementById("mes").style.color ="rgba(255, 255, 255, 0.4)"
}
function monthly(){
    document.getElementById("work").innerHTML = "103hrs"
    document.getElementById("work-sub").innerHTML = "Last Week - 128 horas"
    document.getElementById("play").innerHTML = "23hrs"
    document.getElementById("play-sub").innerHTML = "Last Week - 29 horas"
    document.getElementById("study").innerHTML = "13hrs"
    document.getElementById("study-sub").innerHTML = "Last Week - 19 horas"
    document.getElementById("exercise").innerHTML = "11hrs"
    document.getElementById("exercise-sub").innerHTML = "Last Week - 18 horas"
    document.getElementById("social").innerHTML = "21hrs"
    document.getElementById("social-sub").innerHTML = "Last Week - 23 horas"
    document.getElementById("self").innerHTML = "7hrs"
    document.getElementById("self-sub").innerHTML = "Last Week - 11 horas"
    document.getElementById("dia").style.color ="rgba(255, 255, 255, 0.4)"
    document.getElementById("semana").style.color ="rgba(255, 255, 255, 0.4)"
    document.getElementById("mes").style.color ="white"
}